networks:
  jast_network:
    driver: bridge
    external: false
    name: jast_network

volumes:
  jast_db_data:
  ui_node_modules:

services:
  db:
    image: postgres
    container_name: jast_db
    env_file:
      - .env
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - jast_db_data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - jast_network

  adminer:
    image: adminer
    container_name: jast_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - jast_network

  api:
    build: api
    container_name: jast_api
    depends_on:
      db:
        condition: service_healthy
        restart: true
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - jast_network