services:
  db:
    image: postgres
    container_name: jast_db
    env_file:
      - .env
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      # Set up DB (should be ./db in prod)
      - /home/jheo/jiwanCodes/salsa-tracker/db/init.sql:/docker-entrypoint-initdb.d/init.sql

    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: jast_adminer
    restart: always
    ports:
      - "8080:8080"