networks:
  jast_network:
    driver: bridge

# volumes:
#   jast_db_data:

services:
  db:
    image: postgres
    container_name: jast_db
    env_file:
      - .env
    restart: unless-stopped
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      # Set up DB (should be ./db in prod)
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      # Eventually want to mount a data volume
      # - jast_db_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"
    networks:
      - jast_network

  adminer:
    image: adminer
    container_name: jast_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - jast_network

  ui:
    image: node:18
    container_name: jast_ui
    restart: unless-stopped
    working_dir: /ui  # No extra mounting needed
    volumes:
      - ./ui:/ui  # Mount UI source code in production
      - /ui/node_modules  # Keep node_modules in the container
    ports:
      - "5173:5173"
    command: >
      sh -c "npm install && npm run dev"
    networks:
      - jast_network