AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  LambdaFunctionArn:
    Type: String
    Description: ARN of the deployed Lambda function

Resources:
  SalsaTrackerApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: SalsaTrackerAPI

  CategoriesResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref SalsaTrackerApi
      ParentId: !GetAtt SalsaTrackerApi.RootResourceId
      PathPart: categories  # Creates /categories

  GetCategoriesMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref SalsaTrackerApi
      ResourceId: !Ref CategoriesResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 
          - "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFunctionArn}/invocations"
          - LambdaFunctionArn: !Ref LambdaFunctionArn

  PostCategoriesMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref SalsaTrackerApi
      ResourceId: !Ref CategoriesResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 
          - "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFunctionArn}/invocations"
          - LambdaFunctionArn: !Ref LambdaFunctionArn

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - GetCategoriesMethod
      - PostCategoriesMethod
    Properties:
      RestApiId: !Ref SalsaTrackerApi
      StageName: prod  

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunctionArn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
