Description: Set up CloudFront Distribution and Route53 DNS for the static site

Parameters:
  AcmCertificateArn:
    Type: String
    Description: The ARN of the ACM Certificate for CloudFront

Resources:
  MyCloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: "salsaTracker-CloudFrontOAC"
        Description: "OAC for S3 bucket access"
        OriginAccessControlOriginType: "s3"
        SigningBehavior: "always"
        SigningProtocol: "sigv4" # Use AWS Signature Version 4 (sigv4)

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - salsa-tracker.jiwanheo.xyz
        Origins:
          - Id: S3Origin
            DomainName: !ImportValue SalsaS3DomainName
            S3OriginConfig:
              # AWS docs instruct to leave this field empty if using OAC instead of OAI
              OriginAccessIdentity: ""
            OriginAccessControlId: !Ref MyCloudFrontOAC # Use OAC here
        Enabled: true
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https # Ensure HTTPS is enforced
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false # Do not forward query strings to S3
            Cookies:
              Forward: none # Do not forward cookies
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        DefaultRootObject: index.html
        HttpVersion: http2
        PriceClass: PriceClass_100 # Use the cheapest price class (optional)
        Logging:
          Bucket: !ImportValue SalsaS3DomainName
          IncludeCookies: false
          Prefix: "cloudfront-logs/"
      Tags:
        - Key: Project
          Value: salsa-tracker

#   CloudFrontLogBucketPolicy:
#     Type: AWS::S3::BucketPolicy
#     Properties:
#       Bucket: !Ref S3ForCloudFrontLogs
#       PolicyDocument:
#         Version: "2012-10-17"
#         Statement:
#           - Sid: "AllowCloudFrontLogs"
#             Effect: "Allow"
#             Principal:
#               Service: "cloudfront.amazonaws.com"
#             Action: "s3:PutObject"
#             Resource: !Sub "arn:aws:s3:::${S3ForCloudFrontLogs}/*"
#             Condition:
#               StringEquals:
#                 "AWS:SourceArn": !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}"

#   CloudFrontSiteBucketPolicy:
#     Type: AWS::S3::BucketPolicy
#     Properties:
#       Bucket: !ImportValue S3ForStaticSiteBucketName
#       PolicyDocument:
#         Version: "2012-10-17"
#         Statement:
#           - Sid: "AllowCloudFrontGets"
#             Effect: "Allow"
#             Principal:
#               Service: "cloudfront.amazonaws.com"
#             Action: "s3:GetObject"
#             Resource: !Sub
#               - "arn:aws:s3:::${BucketName}/*"
#               - BucketName: !ImportValue S3ForStaticSiteBucketName
#             Condition:
#               StringEquals:
#                 "AWS:SourceArn": !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}"

#   Route53DNSRecord:
#     Type: AWS::Route53::RecordSet
#     Properties:
#       HostedZoneId: Z04272821ORGI71B464J8
#       Name: jiwanheo.com
#       Type: A
#       AliasTarget:
#         DNSName: !GetAtt CloudFrontDistribution.DomainName # CloudFront distribution domain name
#         HostedZoneId: Z2FDTNDATAQYW2
# Outputs:
#   CloudFrontDistributionId:
#     Description: CloudFront Distribution ID
#     Value: !Ref CloudFrontDistribution
#     Export:
#       Name: CloudFrontDistributionId