Resources:
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Users
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: N
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      GlobalSecondaryIndexes: [] # Can add if needed later

  # MovesTable:
  #   Type: AWS::DynamoDB::Table
  #   Properties:
  #     TableName: Moves
  #     BillingMode: PAY_PER_REQUEST
  #     AttributeDefinitions:
  #       - AttributeName: moveId
  #         AttributeType: N
  #     KeySchema:
  #       - AttributeName: moveId
  #         KeyType: HASH
  #     AttributeDefinitions:
  #       - AttributeName: category
  #         AttributeType: S
  #     GlobalSecondaryIndexes:
  #       - IndexName: CategoryIndex
  #         KeySchema:
  #           - AttributeName: category
  #             KeyType: HASH
  #         Projection:
  #           ProjectionType: ALL

  # UserRatingsTable:
  #   Type: AWS::DynamoDB::Table
  #   Properties:
  #     TableName: UserRatings
  #     BillingMode: PAY_PER_REQUEST
  #     AttributeDefinitions:
  #       - AttributeName: userId
  #         AttributeType: N
  #       - AttributeName: moveId
  #         AttributeType: N
  #     KeySchema:
  #       - AttributeName: userId
  #         KeyType: HASH
  #       - AttributeName: moveId
  #         KeyType: RANGE

  # CountersTable:
  #   Type: AWS::DynamoDB::Table
  #   Properties:
  #     TableName: Counters
  #     BillingMode: PAY_PER_REQUEST
  #     AttributeDefinitions:
  #       - AttributeName: counterName
  #         AttributeType: S
  #     KeySchema:
  #       - AttributeName: counterName
  #         KeyType: HASH
