Resources:
  SalsaS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: salsa-tracker
      VersioningConfiguration:
        Status: Enabled # Enable versioning if needed
      WebsiteConfiguration:
        IndexDocument: index.html
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      Tags:
        - Key: Project
          Value: salsa-tracker
  
Outputs:
  SalsaS3BucketName:
    Description: The domain name of the S3 bucket
    Value: !Ref SalsaS3Bucket
    Export:
      Name: SalsaS3BucketName