name: Deploy React to S3

on:
  push:
    branches:
      - main # Trigger on push to main branch
  pull_request:
    branches:
      - main # Trigger on PRs targeting the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest # This specifies the environment the job will run in

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "us-east-1"
          
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Checkout the code from your repository

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
            node-version: '18'

      - name: Install dependencies
        run: |
          cd ui
          npm install
        
      - name: Build React app
        run: |
          cd ui
          npm run build

      - name: Deploy to S3
        run: |
          aws s3 sync ui/public/ s3://salsa-tracker --exact-timestamps --delete 
        
        