networks:
  jast_network:
    external: true

services:
  alembic:
    build: .
    env_file: 
      - .env
    volumes:
    - .alembic.ini:/alembic/alembic.ini
    - ./migrations:/alembic/migrations
    networks:
      - jast_network
